# Er wordt gebruik gemaakt van Jekyll & Just The Docs
remote_theme: pmarsceill/just-the-docs

title: Introductie Python
color_scheme: dark
search_enabled: true
footer_content: "Jeugdwerking FabLab Erpe-Mere - 2021"

# Aux links for the upper right navigation
aux_links:
  "View the organisation on GitHub":
    - https://github.com/Jeugdwerking-FLEM
